name: golden_ticket
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3
  logging: ^1.2.0
  provider: ^6.0.5
  encrypt: ^5.0.1
  url_launcher: ^6.1.10
  sqflite: ^2.2.8
  confetti: ^0.6.0 # Use the latest version
  path: ^1.8.2
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
